accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
  path('signup/', views.signup, name='signup'),
  path('profile/', views.profile, name='profile'),
  path('profile/edit/', views.edit_profile, name='edit_profile'),
]

home/urls.py
from django.urls import path
from . import views

app_name='home'

urlpatterns = [
  path('', views.index, name='home'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('home.urls', namespace='home')),
    path('products/', include('products.urls', namespace='products')),
    path('categories/', include('categories.urls', namespace='categories')),
]
urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.contrib.auth.models import User

class Profile(models.Model):
  gender = {
    ('Male','Male'),
    ('Female','Female')
  }
  user = models.OneToOneField(User , on_delete=models.CASCADE)
  job = models.CharField(max_length=100, default='not found')
  address = models.CharField(max_length=100, default='not found')
  gender = models.CharField(max_length=100, choices=gender, default='not found')
  phone = models.CharField(max_length=12, default='not found')
  image = models.ImageField(upload_to='profiles/')
  biography = models.TextField(max_length=300, default='not found')
  
  def __str__(self):
    return str(self.user)

@receiver(post_save, sender = User)
def create_user_profile(sender, instance, created, **kwargs):
  if created: 
    Profile.objects.create(user = instance)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile

class SignupForm(UserCreationForm):
  class Meta:
    model = User
    fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']
    
    
class UserForm(forms.ModelForm):
  class Meta:
    model = User
    fields = ['username', 'email', 'first_name', 'last_name']
    
    
class ProfileForm(forms.ModelForm):
  class Meta:
    model = Profile
    fields = ['job', 'phone', 'address', 'gender', 'image', 'biography']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from .forms import SignupForm, UserForm, ProfileForm
from .models import Profile

def signup(request):
  if request.method == 'POST':
    form = SignupForm(request.POST)
    if form.is_valid():
      form.save()
      username = form.cleaned_data['username']
      password = form.cleaned_data['password1']
      user = authenticate(username = username, password = password)
      login(request, user)
      return redirect('/')
  else:
    form = SignupForm()
  return render(request, 'registration/signup.html', {'form': form})


@login_required(login_url='login')
def profile(request):
  profile = Profile.objects.get(user = request.user)
  return render(request, 'profile/profile.html', {'profile': profile})


@login_required(login_url='login')
def edit_profile(request):
  profile = Profile.objects.get(user = request.user)
  if request.method == 'POST':
    user_form = UserForm(request.POST, instance = request.user)
    profile_form = ProfileForm(request.POST, request.FILES, instance = profile)
    if user_form.is_valid and profile_form.is_valid():
      user_form.save()
      myform = profile_form.save(commit = False)
      myform.user = request.user
      myform.save()
      return redirect('/accounts/profile')
  else:
    user_form = UserForm(instance = request.user)
    profile_form = ProfileForm(instance = profile)
  return render(request, 'profile/edit_profile.html', {'user_form': user_form, 'profile_form': profile_form})

accounts/templates/profile/edit_profile.html
{% extends 'base.html' %}
{% block content %}
{% load bootstrap4 %}
<!-- Start Main Section -->
<section class="wrapper__main">
  <!-- Start Edit Profile Section -->
  <div class="content">
    <div class="row">
      <div class="col-md-8 offset-md-2">
        <h4 class="page-title">Edit Profile</h4>
      </div>
    </div>
    <div class="row">
      <div class="col-md-8 offset-md-2">
        <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          {% bootstrap_form user_form %}
          {% bootstrap_form profile_form %}
          <div class="col-12">
            <input ref="btn" type="submit" class="btn btn-primary text-uppercase" value="Edit Profile" />
          </div>
        </form>
      </div>
    </div>
  </div>
  <!-- End Edit Profile Section -->
</section>
<!-- End Main Section -->
{% endblock content %}

accounts/templates/profile/profile.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<!-- Start Main Section -->
<section class="wrapper__main">
  <!-- Start Profile Section -->
  <div class="content">
    <div class="row">
      <div class="col-sm-7 col-4">
        <h4 class="page-title">My Profile</h4>
      </div>
      <div class="col-sm-5 col-8 text-right m-b-30">
        <a href="{% url 'accounts:edit_profile' %}" class="btn btn-primary btn-rounded"><i class="fa fa-plus"></i> Edit Profile</a>
      </div>
    </div>
    <div class="card-box profile-header">
      <div class="row">
        <div class="col-md-12">
          <div class="profile-view">
            <div class="profile-img-wrap">
              <div class="profile-img">
                <a href="#!">
                  {% if profile.image %}
                  <img class="avatar" src="{{profile.image.url}}" alt="profile_img" />
                  {% else %}
                  <img class="avatar" src="{% static 'images/default_img.png' %}" alt="profile-img" />
                  {% endif %}
                </a>
              </div>
            </div>
            <div class="profile-basic">
              <div class="row">
                <div class="col-md-5">
                  <div class="profile-info-left">
                    <h3 class="user-name m-t-0 m-b-0">{{profile.user.first_name}} {{profile.user.last_name}}</h3>
                    <small class="text-muted">{{profile.job}}</small>
                    <div class="staff-id">Profile ID : {{profile.id}} </div>
                  </div>
                </div>
                <div class="col-md-7">
                  <ul class="personal-info">
                    <li>
                      <span class="title">Phone:</span>
                      <span class="text"><a href="">{{profile.phone}}</a></span>
                    </li>
                    <li>
                      <span class="title">Email:</span>
                      <span class="text"><a href="">{{profile.user.email}}</a></span>
                    </li>
                    <li>
                      <span class="title">Address:</span>
                      <span class="text">{{profile.address}}</span>
                    </li>
                    <li>
                      <span class="title">Gender:</span>
                      <span class="text">{{profile.gender}}</span>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="profile-tabs">
      <ul class="nav nav-tabs nav-tabs-bottom">
        <li class="nav-item"><a class="nav-link active" href="#about-cont" data-toggle="tab">About</a></li>
        <!-- <li class="nav-item"><a class="nav-link" href="#bottom-tab2" data-toggle="tab">Profile</a></li> -->
        <!-- <li class="nav-item"><a class="nav-link" href="#bottom-tab3" data-toggle="tab">Messages</a></li> -->
      </ul>
      <div class="tab-content">
        <div class="tab-pane show active" id="about-cont">
          <div class="row">
            <div class="col-md-12">
              <div class="card-box">
                <h3 class="card-title">Experience</h3>
                <div class="experience-box">
                  <p>{{profile.biography}}</p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!--
        <div class="tab-pane" id="bottom-tab2">
          Tab content 2
        </div>

        <div class="tab-pane" id="bottom-tab3">
          Tab content 3
        </div>
        -->
      </div>
    </div>
  </div>
  <!-- End Profile Section -->
</section>
<!-- End Main Section -->
{% endblock content %}