accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
  path('signup/', views.signup, name='signup'),
  path('profile/', views.profile, name='profile'),
  path('profile/edit/', views.edit_profile, name='edit_profile'),
]

categories/urls.py
from django.urls import path
from . import views

app_name='categories'

urlpatterns = [
  path('', views.categories, name='categories'),
  path('add/', views.add_category, name='add_category'),
  path('edit/<int:id>/', views.edit_category, name='edit_category'),
  path('delete/<int:id>/', views.delete_category, name='delete_category'),
]

home/urls.py
from django.urls import path
from . import views

app_name='home'

urlpatterns = [
  path('', views.index, name='home'),
]

products/urls.py
from . import views
from django.urls import path

app_name='products'

urlpatterns = [
  path('', views.products, name='products'),
  path('add/', views.add_product, name='add_product'),
  path('edit/<int:id>/', views.edit_product, name='edit_product'),
  path('delete/<int:id>/', views.delete_product, name='delete_product'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('home.urls', namespace='home')),
    path('products/', include('products.urls', namespace='products')),
    path('categories/', include('categories.urls', namespace='categories')),
]
urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <title>Dashboard</title>
    <!-- Icon Css Incloude-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" />
    <link rel="stylesheet" href="{% static 'font/flaticon.css' %}">
    <!-- Bootstrap CSS File -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" />
    <!-- Custom Css Include-->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
  </head>
  <body>
    <!-- Start Header Section -->
    <header class="wrapper__header">
      <!-- start logo -->
      <div class="logo">
        <a href="{% url 'home:home' %}" class="logo__img">
          <img src="{% static 'images/admin-logo.png' %}" alt="logo-img" />
        </a>
      </div>
      <!-- end Logo -->

      <!-- start sideBar btn -->
      <a href="#!" class="open-aside mobile_btn float-left" id="open-aside" onclick="open_side();"><i class="fa fa-bars"></i></a>
      <a href="#!" class="close-aside mobile_btn float-left" id="close-aside" onclick="close_side();"><i class="fa fa-bars"></i></a>
      <!-- end sidebar btn -->

      <!-- start navbar -->
      <ul class="nav user-menu float-right">
        <!-- start user item -->
        <li class="nav-item dropdown has-arrow">
          <a href="#" class="dropdown-toggle nav-link user-link" data-toggle="dropdown" aria-expanded="false">
            <span class="user-img">
              <img class="rounded-circle" src="{% static 'images/default_img.png' %}" alt="user-img" width="24" />
            </span>
          </a>
          <div class="dropdown-menu" x-placement="bottom-start">
            <a href="{% url 'accounts:profile' %}" class="dropdown-item">My Profile</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item btn" href="{% url 'logout' %}">Logout</a>
          </div>
        </li>
        <!-- end user item -->
      </ul>
      <!-- end navbar -->

      <!-- start mobile user item -->
      <div class="dropdown mobile-user-menu float-right">
        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-ellipsis-v"></i></a>
        <div class="dropdown-menu dropdown-menu-right">
          <a href="{% url 'accounts:profile' %}" class="dropdown-item">My Profile</a>
          <div class="dropdown-divider"></div>
          <span class="dropdown-item btn"><a href="{% url 'logout' %}">Logout</a></span>
        </div>
      </div>
      <!-- End mobile user item -->
    </header>
    <!-- End Header Section -->

    <!-- Start Sidebar Section -->
    <section class="sidebar" id="sidebar">
      <div class="sidebar-menu">
        <ul>
          <li class="menu-title"></li>
          <li>
            <a href="{% url 'home:home' %}"><i class="fa fa-dashboard"></i> Dashboard</a>
          </li>
          <li>
            <a href="{% url 'products:products' %}"><i class="fa fa-shopping-cart"></i> Products</a>
          </li>
          <li>
            <a href="{% url 'categories:categories' %}"><i class="fa fa-list-alt"></i> Categories</a>
          </li>
        </ul>
      </div>
    </section>
    <!-- End Sidebar Section -->

    {% block content %}{% endblock content %}
    
    <!-- This Is All Plugins used-->
    <!-- JQuery Plugins include-->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <!-- Bootstrap 4 Plugins include-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    <!-- Custom JQuery File-->
    <script src="{% static 'js/main.js' %}"></script>
  </body>
</html>