categories/urls.py
from django.urls import path
from . import views

app_name='categories'

urlpatterns = [
  path('', views.categories, name='categories'),
  path('add/', views.add_category, name='add_category'),
  path('edit/<int:id>/', views.edit_category, name='edit_category'),
  path('delete/<int:id>/', views.delete_category, name='delete_category'),
]

home/urls.py
from django.urls import path
from . import views

app_name='home'

urlpatterns = [
  path('', views.index, name='home'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('home.urls', namespace='home')),
    path('products/', include('products.urls', namespace='products')),
    path('categories/', include('categories.urls', namespace='categories')),
]
urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

categories/models.py
from django.db import models

class Category(models.Model):
  category_name = models.CharField(max_length=100, unique=True)
  category_description = models.TextField(max_length=300)
  category_image = models.ImageField(upload_to='categories/')
  
  class Meta:
    verbose_name = ("Category")
    verbose_name_plural = ("Categories")
    
  def __str__(self):
    return self.category_name

categories/forms.py
from django import forms
from .models import Category

class CategoryForm(forms.ModelForm):
  class Meta:
    model = Category
    fields = '__all__'

categories/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from .models import Category
from .forms import CategoryForm

@login_required(login_url='login')
def categories(request):
  categories = Category.objects.all()
  return render(request, 'categories/categories.html', {'categories': categories})


@login_required(login_url='login')
def add_category(request):
  if request.method == 'POST':
    form = CategoryForm(request.POST, request.FILES)
    if form.is_valid():
      form.save()
      return redirect("/categories/")
  else:
    form = CategoryForm()
  return render(request, 'categories/add_category.html', {'form': form})


@login_required(login_url='login')
def edit_category(request, id):
  product = Category.objects.get(id=id)
  if request.method == 'POST':
    form = CategoryForm(request.POST, request.FILES, instance=product)
    if form.is_valid():
      form.save()
      return redirect('/categories/')
  else:
      form = CategoryForm(instance=product)
  return render(request, 'categories/edit_category.html', {'form': form})


def delete_category(request, id):
  delete_category = Category.objects.get(id = id)
  delete_category.delete()
  return redirect('/categories/')

categories/templates/categories/add_category.html
{% extends 'base.html' %}
{% block content %}
{% load bootstrap4 %}
<!-- Start Main Section -->
<section class="wrapper__main">
  <!-- Start Add Category Section -->
  <div class="content">
    <div class="row">
      <div class="col-md-8 offset-md-2">
        <h4 class="page-title">Add Category</h4>
      </div>
    </div>
    <div class="row">
      <div class="col-md-8 offset-md-2">
          <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <div class="col-12">
              <input ref="btn" type="submit" class="btn btn-primary text-uppercase" value="Add Category" />
            </div>
          </form>
        </form>
      </div>
    </div>
  </div>
  <!-- End Add Category Section -->
</section>
<!-- End Main Section -->
{% endblock content %}

categories/templates/categories/categories.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<!-- Start Main Section -->
<section class="wrapper__main">
  <!-- Start Categories Section -->
  <div class="content categories-section">
    <div class="row">
      <div class="col-sm-4 col-3">
        <h4 class="page-title"> Categories </h4>
      </div>
      <div class="col-sm-8 col-9 text-right m-b-20">
        <a href="{% url 'categories:add_category' %}" class="btn btn-primary btn-rounded float-right"><i class="fa fa-plus"></i> Add Category</a>
      </div>
    </div>
    <div class="row" style="margin-top: 27px;">
      <div class="col-md-12">
        <div class="table-responsive">
          <div class="wrapper__dataTables container-fluid">
            <div class="row">
              <div class="col-sm-12">
                <table class="table table-border table-striped custom-table datatable m-b-0 dataTable">
                  <thead>
                    <tr>
                      <th scope="col">#</th>
                      <th scope="col">CATEGORY NAME</th>
                      <th scope="col">DESCRIPTION</th>
                      <th scope="col" class="text-right sorting">ACTION</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for category in categories %}
                    <!-- Start Category Item -->
                    <tr>
                      <td class="product-img" scope="row">
                        {% if category.category_image %}
                        <img src="{{category.category_image.url}}" alt="product-img" />
                        {% else %}
                        <img src="{% static 'images/default_img.png' %}" alt="product-img" />
                        {% endif %}
                      </td>
                      <td class="td-item">{{category.category_name}}</td>
                      <td class="td-item">{{category.category_description}}</td>
                      <td class="text-right">
                        <div class="dropdown dropdown-action patient-action">
                          <a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-ellipsis-v"></i></a>
                          <div class="dropdown-menu dropdown-menu-right">
                            <a href="{% url 'categories:edit_category' category.id %}" class="dropdown-item"><i class="fa fa-pencil m-r-5"></i> Edit</a>
                            <a href="{% url 'categories:delete_category' category.id %}" class="dropdown-item" href="#"><i class="fa fa-trash-o m-r-5"></i> Delete</a>
                          </div>
                        </div>
                      </td>
                    </tr>
                    <!-- End Category Item -->
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- End Categories Section -->
</section>
<!-- End Main Section -->
{% endblock content %}

categories/templates/categories/edit_category.html
{% extends 'base.html' %}
{% block content %}
{% load bootstrap4 %}
<!-- Start Main Section -->
<section class="wrapper__main">
  <!-- Start Edit Category Section -->
  <div class="content">
    <div class="row">
      <div class="col-md-8 offset-md-2">
        <h4 class="page-title">Edit Category</h4>
      </div>
    </div>

    <div class="row">
      <div class="col-md-8 offset-md-2">
          <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <div class="col-12">
              <input ref="btn" type="submit" class="btn btn-primary text-uppercase" value="Edit Category" />
            </div>
          </form>
        </form>
      </div>
    </div>
  </div>
  <!-- End Edit Category Section -->
</section>
<!-- End Main Section -->
{% endblock content %}