home/urls.py
from django.urls import path
from . import views

app_name='home'

urlpatterns = [
  path('', views.index, name='home'),
]

products/urls.py
from . import views
from django.urls import path

app_name='products'

urlpatterns = [
  path('', views.products, name='products'),
  path('add/', views.add_product, name='add_product'),
  path('edit/<int:id>/', views.edit_product, name='edit_product'),
  path('delete/<int:id>/', views.delete_product, name='delete_product'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('home.urls', namespace='home')),
    path('products/', include('products.urls', namespace='products')),
    path('categories/', include('categories.urls', namespace='categories')),
]
urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models
from categories.models import Category

class Product(models.Model):
  product_name = models.CharField(max_length=100, unique=True)
  product_description = models.TextField(max_length=300)
  product_price = models.DecimalField(max_digits=6, decimal_places=2)
  product_category = models.ForeignKey(Category, on_delete=models.CASCADE)
  product_image = models.ImageField(upload_to='products/')

  def __str__(self):
    return self.product_name

products/forms.py
from django import forms
from .models import Product

class ProductForm(forms.ModelForm):
  class Meta:
    model = Product
    fields = '__all__'

products/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Product
from .forms import ProductForm

@login_required(login_url='login')
def products(request):
  products = Product.objects.all()
  context = {'products': products}
  return render(request, 'products/products.html', context)


@login_required(login_url='login')
def add_product(request):
  if request.method == 'POST':
    form = ProductForm(request.POST, request.FILES)
    if form.is_valid():
      form.save()
      return redirect("/products/")
  else:
    form = ProductForm()
  return render(request, 'products/add_product.html', {'form': form})


@login_required(login_url='login')
def edit_product(request, id):
  product = Product.objects.get(id=id)
  if request.method == 'POST':
    form = ProductForm(request.POST, request.FILES, instance=product)
    if form.is_valid():
      form.save()
      return redirect('/products/')
  else:
    form = ProductForm(instance=product)
  return render(request, 'products/edit_product.html', {'form': form})


def delete_product(request, id):
  delete_product = Product.objects.get(id = id)
  delete_product.delete()
  return redirect('/products/')

products/templates/products/add_product.html
{% extends 'base.html' %}
{% block content %}
{% load bootstrap4 %}
<!-- Start Main Section -->
<section class="wrapper__main">
  <!-- Start Add Product Section -->
  <div class="content">
    <div class="row">
      <div class="col-md-8 offset-md-2">
        <h4 class="page-title">Add Product</h4>
      </div>
    </div>
    <div class="row">
      <div class="col-md-8 offset-md-2">
          <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <div class="col-12">
              <input ref="btn" type="submit" class="btn btn-primary text-uppercase" value="Add Product" />
            </div>
          </form>
        </form>
      </div>
    </div>
  </div>
  <!-- End Add Product Section -->
</section>
<!-- End Main Section -->
{% endblock content %}

products/templates/products/edit_product.html
{% extends 'base.html' %}
{% block content %}
{% load bootstrap4 %}
<!-- Start Main Section -->
<section class="wrapper__main">
  <!-- Start Edit Product Section -->
  <div class="content">
    <div class="row">
      <div class="col-md-8 offset-md-2">
        <h4 class="page-title">Edit Product</h4>
      </div>
    </div>
    <div class="row">
      <div class="col-md-8 offset-md-2">
          <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <div class="col-12">
              <input ref="btn" type="submit" class="btn btn-primary text-uppercase" value="Edit Product" />
            </div>
          </form>
        </form>
      </div>
    </div>
  </div>
  <!-- End Edit Product Section -->
</section>
<!-- End Main Section -->
{% endblock content %}

products/templates/products/products.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<!-- Start Main Section -->
<section class="wrapper__main">
  <!-- Start Products Section -->
  <div class="content product-section">
    <div class="row">
      <div class="col-sm-4 col-3">
        <h4 class="page-title">Products</h4>
      </div>
      <div class="col-sm-8 col-9 text-right m-b-20">
        <a href="{% url 'products:add_product' %}" class="btn btn-primary btn-rounded float-right"><i class="fa fa-plus"></i> Add Product</a>
      </div>
    </div>
    <div class="row" style="margin-top: 27px;">
      <div class="col-md-12">
        <div class="table-responsive">
          <div class="wrapper__dataTables container-fluid">
            <div class="row">
              <div class="col-sm-12">
                <table class="table table-border table-striped custom-table datatable m-b-0 dataTable">
                  <thead>
                    <tr>
                      <th scope="col">#</th>
                      <th scope="col">PRODUCT NAME</th>
                      <th scope="col">DESCRIPTION</th>
                      <th scope="col">CATEGORY</th>
                      <th scope="col">PRICE</th>
                      <th scope="col" class="text-right sorting">ACTION</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for product in products %}
                    <!-- Start Product Item -->
                    <tr>
                      <td class="product-img" scope="row">
                        {% if product.product_image %}
                        <img src="{{product.product_image.url}}" alt="product-img" />
                        {% else %}
                        <img src="{% static 'images/default_img.png' %}" alt="product-img" />
                        {% endif %}
                      </td>
                      <td class="td-item">{{product.product_name}}</td>
                      <td class="td-item">{{product.product_description}}</td>
                      <td class="td-item">{{product.product_category}}</td>
                      <td class="td-item">${{product.product_price}}</td>
                      <td class="text-right">
                        <div class="dropdown dropdown-action patient-action">
                          <a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-ellipsis-v"></i></a>
                          <div class="dropdown-menu dropdown-menu-right">
                            <a href="{% url 'products:edit_product' product.id %}" class="dropdown-item"><i class="fa fa-pencil m-r-5"></i> Edit</a>
                            <a href="{% url 'products:delete_product' product.id %}" class="dropdown-item"><i class="fa fa-trash-o m-r-5"></i> Delete</a>
                          </div>
                        </div>
                      </td>
                    </tr>
                    <!-- End Product Item -->
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- End Products Section -->
</section>
<!-- End Main Section -->
{% endblock content %}